"""src/strict_protocol.py must reproduce the frozen strict split's grouping exactly.

The frozen split in datasets/splits_strict/ was generated by
scripts/generate_strict_split.py via scripts/analyze_candidate_component_split_balance.py.
src/strict_protocol.py copies that canonicalization and component logic so CV folds can
be grouped by the same rule. This test rebuilds components on the full master dataset
and asserts the row partition is identical to strict_group_assignment.csv, so the two
implementations cannot drift apart silently.
"""

from pathlib import Path

import pandas as pd

from src.strict_protocol import add_component_group, build_identity_key, canonical_text

ROOT = Path(__file__).resolve().parents[1]
MASTER_PATH = ROOT / "datasets/cleaned/clean_master_dataset.csv"
FROZEN_ASSIGNMENT_PATH = ROOT / "datasets/splits_strict/strict_group_assignment.csv"


def partition(frame: pd.DataFrame, group_column: str) -> set[frozenset[int]]:
    return {
        frozenset(rows)
        for rows in frame.groupby(group_column)["row_index"].apply(list)
    }


def test_component_grouping_matches_frozen_split_assignment():
    master = pd.read_csv(MASTER_PATH)
    frozen = pd.read_csv(FROZEN_ASSIGNMENT_PATH, usecols=["row_index", "component_id"])

    grouped = add_component_group(master).reset_index(names="row_index")

    assert partition(grouped, "strict_component_group") == partition(frozen, "component_id")


def test_canonical_text_matches_protocol_rules():
    assert canonical_text(None) == "__missing__"
    assert canonical_text("  Front   BUMPER ") == "front bumper"
    assert canonical_text(2005.0) == "2005"
    assert canonical_text("ÄÄNI") == canonical_text("ääni")


def test_identity_key_requires_protocol_columns():
    frame = pd.DataFrame({"part_name": ["a"], "brand": ["b"]})
    try:
        build_identity_key(frame)
    except KeyError as error:
        assert "model" in str(error)
    else:
        raise AssertionError("Expected KeyError for missing identity columns")
